language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
script: bash -ex .travis-ci.sh
sudo: required
dist: xenial
env:
  global:
    - TESTS=false
  matrix:
    - OCAML_VERSION=4.10 MODE=unix
    - OCAML_VERSION=4.09 MODE=spt
    - OCAML_VERSION=4.08 MODE=xen
    - OCAML_VERSION=4.08 MODE=hvt
    - OCAML_VERSION=4.07 MODE=xen
    - OCAML_VERSION=4.07 MODE=virtio
